### ISSUE TITLE
MacOS 编译安装完会影响系统。编译SSL会卡住

### ISSUE THREAD

**Issue by chris118** [yedf2/handy#96]
卡住后 ctrl + c 会断在这行

2021/09/09-09:46:35.305649 116ea4e00 INFO /Users/xxx/repo/cpp/handy_src/handy/poller.cc:136 destroying poller 7
2021/09/09-09:46:35.305738 116ea4e00 INFO /Users/xxx/repo/cpp/handy_src/handy/poller.cc:141 poller 7 destroyed

有人遇到过这个问题么？

**Comment by yedf2** [comment]
您好，加入不编译SSL会卡住吗？您是什么情况，需要在生产上面用SSL呢？

**Comment by chris118** [comment]
把handy相关的都卸载掉都不行，还是会卡住，导致有些程序编译就会卡在上面的log的地方进行不下去，不只是SSL

**Comment by yedf2** [comment]
帮忙把完整的复现步骤给一下，相关的命令给出来。只要是能够复现的，都能解决

**Comment by chris118** [comment]
今天又遇到这个问题了，在编译项目的时候又卡在这里了
![image](https://user-images.githubusercontent.com/8801676/137614968-b6f01193-80cc-4562-9bfb-d31f0ab13750.png)

**Comment by chris118** [comment]
今天又遇到这个问题了，克隆项目 https://github.com/ireader/media-server， 编译的时候就卡住了
![image](https://user-images.githubusercontent.com/8801676/137615097-d5cc2b2c-b4e2-40ea-8f7f-2e12f9e7a2a1.png)

**Comment by yedf2** [comment]
我这几天参加dtcc，过几天看看这个问题

**Comment by yedf2** [comment]
我这编译的时候，出现下面问题，您是否能够把你的这个项目弄完整？

gcc -I. -I./include -I../../sdk/include -I../../sdk/libhttp/include -I../librtp/include -I../libmpeg/include -I../libflv/include -I../libmov/include -I../libmkv/include -I../../avcodec/avbsf/include -I../../avcodec/avcodec/include -DOS_MAC -DDEBUG -D_DEBUG -Wall -fPIC -g -Wall -fvisibility=hidden -c -MMD -MP -MF debug.linux/rtsp-media.d -o source/rtsp-media.o source/rtsp-media.c
source/rtsp-media.c:6:10: fatal error: 'sys/path.h' file not found
#include "sys/path.h"
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [source/rtsp-media.o] Error 1
make: *** [all] Error 2

**Comment by chris118** [comment]
问题已找到 编译出来的echo， 运行make install 会安装到 /usr/local/bin 目录， 覆盖了系统的echo， 这样如果后面用到echo这个指令的时候就会启动一个echo server，而不是执行echo指令

**Comment by chengwenwu** [comment]
最新版修复这个问题了吗

**Comment by yedf2** [comment]
handy本身的make install 没有这个问题，它不会将examples里面的echo安装到/usr/local/bin，handy-ssl也不会，这个问题是使用者额外写的makefile导致的 @chengwenwu
